"""
@author:        vfaner
@date:          2019-09-09
@description:   This is a quick script to reformat the appdata.csv 
                file generated by naviance_scraper.py. The reformatted
                file can then be piped into upload_to_staging.py to
                create the college_application_progress and
                college_application_results tables in CollegeData.
"""

from pathlib import Path
from datetime import date
import sys

import pandas as pd


def main():
    csv = sys.argv[1]
    df = pd.read_csv(f'{csv}', dtype=str)

    today = date.today()
    df['file_date'] = today
    df['active_flag'] = (df['stage'] != 'cancelled').astype(int)

    df = df[[
        'studentid',
        'hs_student_id',
        'naviance_school_id',
        'district_school_id',
        'naviance_college_id',
        'ceeb_code',
        'stage',
        'type',
        'result_code',
        'active_flag',
        'file_date',
        'attending',
    ]]

    df.to_csv('appdata.csv', index=False)


if __name__ == '__main__':
    main()
